import { features } from "../../constants";
import styles, { layout } from "../../style";
import Button from "./Button";
import { useGlobalContext } from "../../context/SidebarContext";
import { useSelector } from "react-redux";
import { Link } from "react-router-dom";

const FeatureCard = ({ icon, title, content, index }) => (
  <div className={`flex flex-row p-6 rounded-[20px] ${index !== features.length - 1 ? "mb-6" : "mb-0"} feature-card`}>
    <div className={`w-[64px] h-[64px] rounded-full ${styles.flexCenter} bg-dimBlue`}>
      <img src={icon} alt="star" className="w-[50%] h-[50%] object-contain" />
    </div>
    <div className="flex-1 flex flex-col ml-3">
      <h4 className="font-poppins font-semibold text-white text-[18px] leading-[23.4px] mb-1">
        {title}
      </h4>
      <p className="font-poppins font-normal text-dimWhite text-[16px] leading-[24px]">
        {content}
      </p>
    </div>
  </div>
);

const Business = () =>  {
  const { openSidebar } = useGlobalContext();
  const { userInfo }  = useSelector((state) => state.auth);
return (
<section id="features" className={layout.section}>
    <div className={layout.sectionInfo}>
      <h2 className={styles.heading2}>
        You deposit money, <br className="sm:block hidden" /> we’ll create
        extra money with crypto.
      </h2>
      <p className={`${styles.paragraph} max-w-[470px] my-5`}>
      Inviters can get bonus proportional to the transaction volume 
      generated by their invitees. The maximum bonus for a valid 
      invitation is Unlimit USDT.
      </p>

      {userInfo?
        <Link to={'/admin'}>
            <Button />
        </Link>:
        <button onClick={openSidebar}>
          <Button />
        </button>}
    </div>

    <div className={`${layout.sectionImg} flex-col`}>
      {features.map((feature, index) => (
        <FeatureCard key={feature.id} {...feature} index={index} />
      ))}
    </div>
  </section>
);
};

export default Business;
